.\" %W% %G%
.TH CIDCALL 1
.SH NAME
.B cidcall
- view calls, hangups, and messages the NCID call file
.SH SYNOPSIS
.B cidcall
[-r | -chmo] [cidlog]
.SH DESCRIPTION
The
.B cidcall
scrip displays the cidcall.log file.
.SS "OPTIONS"
.PD 0
.TP 14
.B -r
Display the raw call file.
.br
Default: format the call file.
.TP
.B -c
Display CID lines (incoming calls) in the call file.
.TP
.B -h
Display HUP lines (terminated calls) in the call file.
.TP
.B -m
Display MSG lines (messages) in the call file.
.TP
.B -o
Display OUT lines (outgoing calls) in the call file.
.PD
.SS "Arguments"
.PD 0
.TP 14
.B cidlog
The NCID call file.
.br
Default: /var/log/cidcall.log
.PD
.SH SEE ALSO
ncidd.conf.5,
ncidd.alias.5,
ncidd.blacklist.5,
cidalias.1,
cidupdate.1
