.\" %W% %G%
.TH NCID 1
.SH NAME
.B ncid\^
- Network Caller ID Client
.SH SYNOPSIS
.B ncid\^
[options] [arguments]
.PP
.B tivocid\^
[options] [arguments]
.PP
.I Options:\^
.PP
.nf
[--no-gui]
[--all             | -A]
[--call-prog       | -C]
[--delay seconds   | -D seconds]
[--program PROGRAM | -P PROGRAM]
[--raw             | -R]
[--verbose         | -V]
[--ring count      | -r count]
.fi
.PP
.I Arguments:\^
.PP
.nf
[IP_ADDRESS | HOSTNAME]
[PORT_NUMBER]
.fi
.SH DESCRIPTION
.B NCID
displays Caller ID information sent to it by the Caller ID server.
In the default GUI mode, if the server is configured to send the
CID Call Log, it will load the call log in the CID log window at
startup.  The call log is updated by \fIncid\fR whenever a call
is received.
.PP
.B NCID
also has a message window that will send a single line message
to the server which, in turn, will send it to all connected clients.
.PP
.B NCID
runs on Linux and Windows 98, ME, XP, 2000, NT.  In the GUI mode, it
will pop up, and go on top whenever a call comes in.  In addition,
it will display itself on whatever desktop is active in Linux.
If \fIncid\fR is given the --no-gui option, it will either output
to a external program, output module, or use the verbose mode to
display the CID information in a terminal window.
.PP
If \fIncid\fR is named \fItivocid\fR, it will start in a no-gui mode
and output to a external program called \fIout2osd\fR which displays
the Caller ID on a TV using a TiVo.
.PP
If \fIncid\fR is configured to output to a external program, it will
test for it, and if it is not found, or if it is not executable,
it will terminate with a error message.
.PP
The configuration file for \fIncid\fR is /etc/ncid/ncid.conf.
.PP
Four output modules are provided, customize as needed in the
/etc/ncid/ncidscript.conf file:
.PD 0
.TP 12
.B ncid-mythtv
Displays Caller ID on a TV using MythTV.
.TP
.B ncid-page
Sends a page or cell phone notification, with the CID information,
when a call is received.
Must set $ADDRESS, in the script, to the pager address.
.TP
.B ncid-speak
Speaks the caller name when a call is received, using \fIfestival\fB.
Script can be modified to speak any of the CID information.
.TP
.B ncid-samba
Send a SMB popup message containing the Caller ID information.
.PD
.PP
Whenever the server connection is broken, \fIncid\fR will try to reconnect
once a minute.  It provides a visual record of the countdown and number
of tries.
.PP
The file menu provides three menu items in the GUI mode:
.PD 0
.TP 11
.B reconnect
provides an immediate reconnect and a reload of the call log file.
This provides a way to synchronize \fIncid\fR with the server call log in
the event of a network problem.
.TP
.B clear
clears the call log
.TP
.B quit
terminates \fIncid\fR.
.PD
.SH "OPTIONS"
.PD 0
.TP 30
.B --no-gui
Do not display CID information using a GUI
.br
Default: display CID using a GUI, except if called tivocid
.TP
.B --all | -A
output: date time number name
.br
Default output: name number
.TP
.B --call-prog | -C
output name and number to external program, or output module
.br
Default: does not output to external program unless name is tivocid
.TP
.B --delay seconds | -D seconds
delay between server connection attempts
.br
Default: 60 seconds
.TP
.B --prog PROGRAM | -P PROGRAM
the display or helper program to use
.br
Default PATH: /usr/share/ncid
.br
Default PROGRAM: ncid-speak
.TP
.B --raw | -R
display data received from the CID Server
.br
Default: raw data not displayed
.TP
.B --ring count | -r count
call output module on ring count
.br
Default: output module called as soon as CID received
.TP
.B --verbose | -V
display formatted CID information, including CID log file
.br
Default: silent
.PD
.SS "Arguments"
.PD 0
.TP 30
.B IP_ADDRESS | HOSTNAME
set the IP Address
.br
Default: 127.0.0.1 (localhost)
.TP
.B PORT_NUMBER
set the port number
.br
Default: 3333
.PD
.SH FILES
/etc/ncid/*
.br
/usr/share/ncid/*
.SH EXAMPLES
.nf
# run ncid in a terminal window, server on remote host
ncid --no-gui tardis.drwho.home
# output Caller ID to output module
ncid --no-gui --call-prog --program ncid-speak
# output NAME & NUMBER to GUI and output module
ncid --call-prog --program /usr/local/bin/ncid-speak
# output NAME & NUMBER to GUI and all CID info to output module
ncid --all --call-prog --program ncid-page
# output all CID info to output module after third ring
ncid --no-gui --all --call-prog --ring 3 --program ncid-page
# run ncid on a TiVo, server on remote host
tivocid 192.168.0.1
ncid --no-gui --call-prog --program /var/hack/bin/out2osd 192.168.0.1
.fi
.SH SEE ALSO
lcdncid.1, out2osd.1, ncidd.8, ncidd.conf.5 ncidd.alias.5
