.\" %W% %G%
.TH NCIDD.CONF 5
.SH NAME
.B ncidd.conf
- ncidd configuration file
.SH DESCRIPTION
The \fIncidd.conf\fR file contains the configuration information for
\fIncidd\fR, the Network Caller ID Server.
.PP
The \fIncidd.conf\fR file is used to set options.
Options are set on a command line.
A line is broken up into words.
A word is either a string of non-blank characters, everything
between double quotes, or an equal sign.
.PP
The \fIncidd.conf\fR file understands 5 types of lines:
.TP
.B blank line
skip it
.TP
.B comment line, beginning with '#'
skip it
.TP
.B command lines, beginning with 'send'
send DATATYPE
.RS 11
where DATATYPE = cidlog, cidinfo
.RE
.TP
.B command lines, beginning with 'set'
set ITEM = VALUE [ITEM = VALUE] [...]
.RS 11
where ITEM = cidlog, cidlogmax, datalog, initcid, initstr,
lockfile, noserial, port, ttyclocal, ttyport, ttyspeed, nomodem,
verbose
.RE
.SH EXAMPLES
Send the CID log to each client at connect:
.RS 0
	send cidlog
.RE
.PP
Send the ring count, at each ring, to each client
.RS 0
	send cidinfo
.RE
.PP
Send outgoing calls to each client
.RS 0
    send cidout
.RE
.PP
Set the modem for Caller ID:
.RS 0
	set initcid = "AT#CID=1"
.RE
.PP
Set the modem port:
.RS 0
	set ttyport=/dev/ttyS1
.RE
.PP
Set the Telephone Line Indicator for the modem:
.RS 0
	set lineid = POTS
.RE
.PP
Configure ncidd to ignore modems that do not send Caller ID:
.RS 0
	set gencid = 0
.RE
.PP
Use a modem and possibly a Gateway to obtain the Caller ID:
.RS 0
	set noseriel = 0
.RE
.PP
Only use Gateways to obtain the Caller ID:
.RS 0
	set noseriel = 1
.RE
.SH SEE ALSO
ncid.1, ncidtools.1, lcdncid.1, out2osd.1, ncidd.8 ncidd.alias.5
