.\" %W% %G%
.TH NCID-YAC 1
.SH NAME
.B ncid-yac
- send Caller ID to YAC listeners
.SH SYNOPSIS
ncid --no-gui --program
.B ncid-yac
.SH DESCRIPTION
The
.B ncid-yac
output module sends the Caller ID or message to YAC listeners.
.SH REQUIREMENTS
YAC listener
.TP
URL:
http://www.sunflowerhead.com/software/yac/
.SH FILES
/etc/ncid/conf.d/ncid-yac.conf
.br
/usr/share/ncid/ncid-yac
.SH SEE ALSO
ncidd.8,
ncid-modules.7,
ncid.1,
ncid-alert.1,
ncid-initmodem.1,
ncid-kpopup.1,
ncid-mythtv.1,
ncid-notify.1,
ncid-page.1,
ncid-samba.1,
ncid-skel.1,
ncid-wakeup.1,
ncid-speak.1
