.\" %W% %G%
.TH NCID-SAMBA 1
.SH NAME
.B ncid-samba
- send Caller ID to samba to create a popup
.SH SYNOPSIS
ncid --no-gui --program
.B ncid-samba
.SH DESCRIPTION
The
.B ncid-samba
output module sends the Caller ID or message to a Windows computer.
.SH REQUIREMENTS
Windows computer
.SH FILES
/etc/ncid/conf.d/ncid-samba.conf
.br
/usr/share/ncid/ncid-samba
.SH SEE ALSO
ncidd.8,
ncid.1,
ncid-alert.1,
ncid-initmodem.1,
ncid-kpopup.1,
ncid-mythtv.1,
ncid-notify.1,
ncid-page.1,
ncid-skel.1,
ncid-speak.1,
ncid-wakeup.1,
ncid-yac.1
