.\" %W% %G%
.TH NCIDTOOLS 1
.SH NAME
.B cidcall
- view calls, hangups, and messages the NCID call file
.PP
.B cidalias
- view alias definitions in the NCID alias file
.PP
.B cidupdate
- update aliases in the NCID call file
.SH SYNOPSIS
.B cidcall
[-r | -chmo] [callfile]
.PP
.B cidalias
[-r] [aliasfile]
.PP
.B cidupdate
[-A aliasfile] [-C callfile] [newcallfile]
.SH DESCRIPTION
The script,
.BR cidcall ,
displays the cidcall.log file.
.PP
The script,
.BR cidalias ,
displays the aliases in the ncidd.alias file.
.PP
The Script,
.BR cidupdate ,
updates the cidcall.log file using the aliases found in the ncidd.alias file.
.SH "OPTIONS"
.PD 0
.TP 14
.B -r
Display the raw call file or alias definition.
.br
Default: format the call file or alias definition.
.TP
.B -c
Display CID lines (incoming calls) in the call file.
.TP
.B -h
Display HUP lines (terminated calls) in the call file.
.TP
.B -m
Display MSG lines (messages) in the call file.
.TP
.B -o
Display OUT lines (outgoing calls) in the call file.
.TP
.B -A aliasfile
Set the alias file to \fIaliasfile\fR
.br
Default: /etc/ncid/ncidd.alias
.TP
.B -C callfile
Set the call file to \fIcallfile\fR
.br
Default: /var/log/cidcall.log
.PD
.SS "Arguments"
.PD 0
.TP 14
.B callfile
The NCID call file.
.br
Default: /var/log/cidcall.log
.TP
.B aliasfile
The ncidd alias file.
.br
Default: /etc/ncid/ncidd.alias
.TP
.B newcallfile
The updated call file.
.br
Default: <callfile>.new
.PD
.SH SEE ALSO
ncidd.conf.5, ncidd.alias.5, ncidd.blacklist.5
