.\" %W% %G%
.TH NCIDSCRIPTS 1
.SH NAME
.B ncidrotate\^
- keep lines in logfile after it is rotated
.PP
.B ncid-page\^
- send CID to a pager or cell phone
.PP
.B ncid-samba\^
- send CID to samba to create a popup
.PP
.B ncid-speak\^
- send CID to a text-to-speach program
.PP
.B ncid-mythtv\^
- display CID on MythTV using mythtvosd
.PP
.B ncid-tivo\^
- display CID on TiVo using text2osd
.SH SYNOPSIS
.B ncidrotate\^
{prerotate|postrotate}
.PP
.B ncid-page\^
CIDdate CIDtime CIDnumber CIDname CIDline
.PP
.B ncid-samba\^
CIDdate CIDtime CIDnumber CIDname CIDline
.PP
.B ncid-speak\^
CIDdate CIDtime CIDnumber CIDname CIDline
.PP
.B ncid-mythtv\^
CIDdate CIDtime CIDnumber CIDname CIDline
.PP
.B ncid-tivo\^
CIDdate CIDtime CIDnumber CIDname CIDline
.SH DESCRIPTION
These are CID output modules and are normally located in the
.BR /usr/share/ncid
directory.
.PP
.B Ncidrotate
is called by
.I /etc/logrotate.d/ncidd
and will keep a number of lines in the logfile after rotation.
The default is 0 lines kept.  The configuration file for
logrotate is
.I /etc/ncid/ncidrotate.conf
.PP
The client,
.BR ncid ,
can be configured to call
.BR ncid-page ,
.BR ncid-samba ,
.BR ncid-speak .
or
.BR ncid-mythtv .
The configuration file for the scripts is
.I /etc/ncid/ncidscript.conf
.PD
.SH FILES
/etc/ncid/ncidrotate.conf
.br
/etc/ncid/ncidscript.conf
.SH SEE ALSO
ncid.1,
ncidscript.conf.5,
ncidd.8
