.\" %W% %G%
.TH NCIDTOOLS 1
.SH NAME
.B cidlog
- view Caller ID log file
.PP
.B cidalias
- view Caller ID alias definitions
.PP
.B cidupdate
- update Caller ID aliases in log file
.SH SYNOPSIS
.B cidcall
[-r | -m] [cidlog]
.PP
.B cidalias
[-r] [aliasfile]
.PP
.B cidupdate
[-a aliasfile] [-l cidlog] [newcidlog]
.SH DESCRIPTION
The script,
.BR cidcall ,
displays the current CID call file.
.PP
The script,
.BR cidalias ,
displays the aliases in the ncidd.alias file.
.PP
The Script,
.BR cidupdate ,
updates the CID log file using the aliases found in the ncidd.alias file.
.SH "OPTIONS"
.PD 0
.TP 14
.B -r
Display the raw log file or alias definition.
.br
Default: format the log file or alias definition.
.TP
.B -m
Display messages sent.
.TP
.B -a aliasfile
Set the alias file to \fIaliasfile\fR
.br
Default: /etc/ncid/ncidd.alias
.TP
.B -c cidlog
Set the CID call file to \fIcidlog\fR
.br
Default: /var/log/cidcall.log
.PD
.SS "Arguments"
.PD 0
.TP 14
.B cidlog
The CID call file.
.br
Default: /var/log/cidcall.log
.TP
.B configfile
The ncidd configuration file.
.br
Default: /etc/ncid/ncidd.conf
.TP
.B newcidlog
The updated CID log file.
.br
Default: cidcall.log.new
.PD
.SH SEE ALSO
ncidd.conf.5, ncidd.alias.5
