.\" %W% %G%
.TH NCIDMODULES.CONF 5
.SH NAME
.B ncidmodules.conf\^
- ncid module configuration file
.SH DESCRIPTION
The \fIncidmodules.conf\fR file contains the configuration information for
\fIncid\fR, output modules and the init or rc file.
.PP
The \fIncidmodules.conf\fR file is used to set options for
.IR ncid-mythtv .
.IR ncid-page ,
.IR ncid-samba ,
.IR ncid-speak .
.IR ncid-tivo .
and
.IR ncid-yac .
.PP
The \fIncidmodules.conf\fR file understands 3 types of lines:
.TP
.B blank line
skip it
.TP
.B comment line, beginning with '#'
skip it
.TP
.B shell variable set lines.
.PP
See ncidsmodules.conf for more details on the variables that
can be set.
.SH EXAMPLES
ncid command line options to call ncid-page at ring number 4:
.RS 0
	ncid --call-prog --program ncid-page --ring 4
.RE
.PP
set the email address for ncid-page in ncidmodules.conf:
.RS 0
	PageTo=cellphone@isp.com
.RE
.SH SEE ALSO
ncid.1, ncidtools.1, lcdncid.1, out2osd.1, ncidd.8 ncidmodules.1
