.\" %W% %G%
.TH NCID 1
.SH NAME
.B ncid
- Network Caller ID Client
.SH SYNOPSIS
.B ncid\^
[options] [arguments]
.PP
.B tivocid\^
[options] [arguments]
.PP
.B tivoncid\^
[options] [arguments]
.PP
.I Options:\^
.PP
.nf
[--no-gui]
[--call-out          | -C]
[--delay seconds     | -D seconds]
[--message           | -M]
[--noexit            | -X]
[--program PROGRAM   | -P PROGRAM]
[--pidfile FILE      | -p PIDFILE]
[--raw               | -R]
[--ring count        | -r count]
[--tivo              | -T]
[--PopupTime seconds | -t seconds]
[--verbose           | -V]
.fi
.PP
.I Arguments:\^
.PP
.nf
[IP_ADDRESS | HOSTNAME]
[PORT_NUMBER]
.fi
.SH DESCRIPTION
.B Ncid
displays Caller ID information sent to it by the Caller ID server.
In the default GUI mode, if the server is configured to send the
CID Call Log, it will load the call log in the CID log window at
startup.  The call log is updated by \fIncid\fR whenever a call
is received.
.PP
.B Ncid
also has a message window that will send a single line message
to the server which, in turn, will send it to all connected clients.
.PP
.B Ncid
runs on Linux and Windows 98, ME, XP, 2000, NT.  In the GUI mode, it
will pop up, and go on top whenever a call comes in.  In addition,
it will display itself on whatever desktop is active in Linux.
If \fIncid\fR is given the --no-gui option, it will either output
to a external program, output module, or use the verbose mode to
display the CID information in a terminal window.
.PP
If \fIncid\fR is named \fItivocid\fR, it will start in a no-gui mode
and output to a external program called \fIout2osd\fR which displays
the Caller ID on a TV using a TiVo.
.PP
If \fIncid\fR is named \fItivoncid\fR, it will start in a no-gui mode
and output to a module called \fIncid-tivo\fR which displays
the Caller ID on a TV using a TiVo.  This option uses the TiVo
program, \fItext2osd\fR, instead of \fIout2osd\fR.
.PP
If \fIncid\fR is configured to output to a external program, it will
test for it, and if it is not found, or if it is not executable,
it will terminate with a error message.
.PP
The configuration file for \fIncid\fR is /etc/ncid/ncid.conf.
.PP
The distributed output modules are listed in the ncidmodules man page,
can be customized as needed in the /etc/ncid/ncidmodules.conf file:
.PP
Whenever the server connection is broken, \fIncid\fR will normally try
to reconnect once a minute.  It provides a visual record of the countdown
and number of tries.
If the delay between attempts is set to
zero seconds, \fIncid\fR will not attempt a reconnect.
.PP
The file menu provides three menu items in the GUI mode:
.PD 0
.TP 11
.B reconnect
provides an immediate reconnect and a reload of the call log file.
This provides a way to synchronize \fIncid\fR with the server call log in
the event of a network problem.
.TP
.B clear
clears the call log
.TP
.B quit
terminates \fIncid\fR.
.PD
.SH "OPTIONS"
.PD 0
.TP
.B --no-gui
Do not display CID information using a GUI
.br
Default: display CID using a GUI, except if called tivocid
.TP
.B --call-out | -C
Display outgoing call information, if the server supports it.
.br
Default: Do not display outgoing calls.
.TP
.B --delay SECONDS | -D SECONDS
Delay SECONDS between server connection attempts if SECONDS > 0.
.br
Only one attempt to connect to server if SECONDS = 0.
.br
Default: 60 seconds
.TP
.B --message | -M
Send messages to the output modules
.B --noexit | -X
Configure ncid to to ignore the close window button.
.TP
.B --pidfile | -p
Name of PID file to create.
Set to \fI/var/run/ncid.pid\fR in a rc or init script when used as a service.
Set to \fI/var/run/OUTPUTMODULE.pid\fR in a rc or init script when used as
a service and when using a output module.
There is no default.  If pidfile is not set, no pid file will be used.
.TP
.B --program PROGRAM | -P PROGRAM
Output the Caller ID information to the external program or output module.
PROGRAM is the name of the output module (program) to use.
The selected module is sent the Caller ID information.
Outgoing call information is also sent if the call-out option is enabled.
A message is also sent, if the message option is enabled.
.br
Default module PATH: /usr/share/ncid
.TP
.B --raw | -R
display data received from the CID Server
.br
Default: raw data not displayed
.TP
.B --ring count | -r count
Call output module on specific ring count.
.br
For modems that indicate RING, count can be: 0 2 3 4 5 6 7 8 9
.br
For VoIP, using a SIP gateway, count can be: -2 -1
.br
A count of -1 indicates a hangup before answer.
.br
A count of -2 indicates a hangup after answer.
.br
Default: output module called as soon as CID received
.TP
.B --Tivo | -T
This option is for a TiVo using out2osd or text2osd
.br
Changes output to 2 lines: name number line
.br
Default output is 5 lines: date time number name line
.TP
.B --PopupTime seconds | -t seconds
Time for the popup to stay on top of all windows.
Range is 1 second to 99 seconds
.br
Default popup time os 5 seconds
.TP
.B --verbose | -V
display formatted CID information, including CID log file
.br
Default: silent
.PD
.SS "Arguments"
.PD 0
.TP 30
.B IP_ADDRESS | HOSTNAME
set the IP Address
.br
Default: 127.0.0.1 (localhost)
.TP
.B PORT_NUMBER
set the port number
.br
Default: 3333
.PD
.SH FILES
/etc/ncid/*
.br
/usr/share/ncid/*
.SH EXAMPLES
.nf
# run ncid in a terminal window, server on remote host
ncid --no-gui tardis.drwho.home

# only speak Caller ID
ncid --no-gui --program ncid-speak

# send CID output to GUI and speak it
ncid --program /usr/local/bin/ncid-speak

# send CID output to a cell phone after third ring
ncid --no-gui --program ncid-page --ring 3

# send CID output to a cell phone on hangup before answer
ncid --no-gui --program ncid-page --ring -1

# run ncid on a TiVo using out2osd, server on remote host
tivocid 192.168.0.1
.fi
.SH SEE ALSO
ncidd.8, sip2ncid.8,
ncid2ncid.1, ncidmodules.1, ncidrotate.1, ncidtools.1, yac2ncid.1,
ncid.conf.5, 
