.\" %W% %G%
.TH NCID.CONF 5
.SH NAME
.B ncid.conf
- ncid configuration file
.SH DESCRIPTION
The \fIncid.conf\fR file contains the configuration information for
\fIncid\fR, the Network Caller ID Client.  Use \fIncid.conf\fR to
configure ncid every time it is started, but use \fIncidmodules.conf\fR
to configure ncid for a particular output module.  For example, use
\fIncid.conf\fR to configure ncid for the server address, but use
\fIncidmodules.conf\fR to configure ncid to for ncid-page.
.PP
The \fIncid.conf\fR file is a tcl/tk configuration file used to set options.
.PP
The \fIncid.conf\fR file understands 3 types of lines:
.TP
.B blank line
ignored
.TP
.B comment line, beginning with '#'
ignored
.TP
.B command lines, beginning with 'set'
.PP
See ncid.conf for a complete list of variables to set and
what the default values are.
.SH EXAMPLES
Set ncid to use the page output module:
.RS 0
	set ProgName     \fIncid-page\fR
.RE
.PP
Set ncid to format its output for the US and include the 1.
The number output display will be 1-XXX-XXX-XXXX instead of XXX-XXX-XXXX:
.RS 0
    set NoOne       0
.RE
.PP
Set ncid to format its number output display for Sweden:
The number output display will be 0X-XXXXXXXX, 0XX-XXXXXXX, 0XXX-XXXXX, etc:
.RS 0
    set Country     "SE"
.RE
.SH SEE ALSO
ncid.1, ncidtools.1, lcdncid.1, out2osd.1, ncidd.8 ncidd.alias.5,
ncidd.conf.5
