.\" %W% %G%
.TH NCID-NOTIFY 1
.SH NAME
.B ncid-notify
- send a NCID notification to your Android or iOS device
.SH SYNOPSIS
ncid --no-gui --program
.B ncid-notify
.SH DESCRIPTION
The
.B ncid-notify
is a NCID notification program that uses NMA (Notify My Android),
Prowl, or both NMA and Prowl
It displays the Caller ID or message on a Android device, a iOS device,
or one of each.
.SH REQUIREMENTS
.TP
Android Device Requirements:
The "Notify My Android" app on your Android device.
.br
Registration at NMA website http://www.notifymyandroid.com/
.br
Generated API key to place in configuration file.
.TP
iOS Device Requirements:
The Prowl (Growl client for iOS) app from the app store
.br
Registration at Prowl website http://www.prowlapp.com/
.br
Generated API key to place in configuration file.
.SH FILES
/etc/ncid/conf.d/ncid-notify.conf
.br
/usr/share/ncid/ncid-notify
.br
/etc/ncid/key-prowl-api
.br
/etc/ncid/key-nma-api
.br
/etc/ncid/key-prowl-provider
.br
/etc/ncid/key-nma-developer
.SH SEE ALSO
ncidd.8,
ncid-modules.7,
ncid.1,
ncid-alert.1,
ncid-initmodem.1,
ncid-kpopup.1,
ncid-mythtv.1,
ncid-page.1,
ncid-samba.1,
ncid-skel.1,
ncid-speak.1,
ncid-wakeup.1,
ncid-yac.1
