.\" %W% %G%
.TH NCID-MYTHTV 1
.SH NAME
.B ncid-mythtv
- display Caller ID on MythTV using mythtvosd
.SH SYNOPSIS
ncid --no-gui --program
.B ncid-mythtv
.SH DESCRIPTION
The
.B ncid-mythtv
output module is a MythTV display program.  It displays the Caller ID or
message on a TV.
.SH REQUIREMENTS
MythTV software
.SH FILES
/etc/ncid/conf.d/ncid-mythtv.conf
.br
/usr/share/ncid/ncid-mythtv
.SH SEE ALSO
ncidd.8,
ncid-modules.7,
ncid.1,
ncid-alert.1,
ncid-initmodem.1,
ncid-kpopup.1,
ncid-notify.1,
ncid-page.1,
ncid-samba.1,
ncid-skel.1,
ncid-speak.1,
ncid-wakeup.1,
ncid-yac.1
