#! /bin/sh

# Created by John L. Chmielewski on Sun June 11, 2006

# script runs ncidd in debug mode on port 3334 for testing
# a server or a client

[ -x "$1" ] || \
{
    echo "Usage: `basename $0` {PATH/ncidd} [-nciddOption(s)]"
    exit 0
}

NCID="$1"
shift

touch T-call.log T-data.log T-ncidd.conf T-ncidd.alias
$NCID -Dv3 \
      -c T-call.log \
      -d T-data.log \
      -L T-server.log \
      -A T-ncidd.alias \
      -C T-ncidd.conf \
      -N 1 \
      -p 3334 \
      -s cidlog \
      -s cidinfo \
      $*
