#! /bin/sh

# Created by John L. Chmielewski on Sun June 11, 2006
# Last modified by jlc on Tue Mar 31, 2009

# script runs ncidd in debug mode on port 3334 for testing
# a server or a client

[ -x "$1" ] || \
{
    echo "Usage: `basename $0` {PATH/ncidd} [-nciddOption(s)]"
    exit 0
}

NCID="$1"
shift

touch T-data.log T-config T-alias T-blacklist
$NCID -Dv3 \
      -c T-call.log \
      -d T-data.log \
      -L T-logfile \
      -A T-alias \
      -B T-blacklist \
      -C T-config \
      -P T-pid \
      -p 3334 \
      -s cidlog \
      -s cidinfo \
      -s callout \
      -t ./vmodem0 \
      $*
