#! /bin/sh

# Created by John L. Chmielewski on Sun June 11, 2006
# Last modified by jlc on Thu Mar 27, 2014

# script runs ncidd in debug  or Mac OS X Launchd mode on port 3334
# for testing a server or a client

NCID="$1"
MODE="-D"

usage(){
    echo "Usage: `basename $0` {<path>/ncidd} [--osx-launchd] [-nciddOption(s)]"
    exit 0
}

[ -x "$1" ] || { usage; exit 0; }

[ "$2" = "--osx-launchd" ] && \
{
    MODE="$2"
    shift
}
shift

touch T-data

[ -f T-conf ] || \
{
# create test configuration file
cat << EOF > T-conf
set verbose = 3
set cidlog = T-call
set datalog = T-data
set cidalias = T-alias
set blacklist = T-black
set whitelist = T-white
set pidfile = T-pid
set ttyport = vmodem0
set port = 3334
send cidlog
send cidinfo
EOF
}

[ -f T-call ] || \
{
    # create test call log from running call log
    cp /var/log/cidcall.log T-call
}

[ -f T-alias ] || \
{
    # create test alias file from default alias file
    cp ../server/ncidd.alias T-alias
}

[ -f T-black ] || \
{
    # create test blacklist file from default blacklist file
    cp ../server/ncidd.blacklist T-black
}

[ -f T-white ] || \
{
    # create test whitelist file from default whitelist file
    cp ../server/ncidd.whitelist T-white
}

# default server command line
# command lines options can be added
$NCID $MODE -C T-conf -L T-log $*
