#!/usr/bin/perl

# Created by John L. Chmielewski on Fri Mar 14, 2003
# Last updated by jlc on Tue Mar 31, 2009

($testfile = shift) || ($testfile = "testclient.data");

open(OUTPUT, '|nc -l localhost 3334') || die "Could not open netcat\n";
open(TESTFILE, $testfile) || die "Could not open $testfile\n";

print "Connect client to port 3334 to test, for example: ncid 3334\n\n";
print "Then press <ENTER> multiple times to:\n";
print "    send MSG:     lines\n";
print "    send CIDLOG:  lines\n";
print "    send CID:     line\n";
print "    send CIDINFO: lines\n";
print "    end  program\n\n";

select(OUTPUT);
$| = 1;

while (<TESTFILE>) {
    if (/^#/) { next; }
	if (/\w.*/) { print STDOUT; print; }
	else { $response = <STDIN>; }
}

exit 0;
