#!/bin/sh
# postrm script for ncid
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

update-rc.d -f ncid-mythtv remove
update-rc.d -f ncid-page remove
update-rc.d -f ncid-popup remove
update-rc.d -f ncid-samba remove
update-rc.d -f ncid-speak remove
update-rc.d -f ncid-yac remove
update-rc.d -f ncidsip remove
update-rc.d -f sip2ncid remove
update-rc.d -f yac2ncid remove
update-rc.d -f ncidd remove

exit 0
