#!/bin/sh
# postrm script for ncid
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
    purge|remove)
    ;;
    upgrade)
        # restart services that are running
        # a service could have been installed by another package
        for script in /usr/share/ncid/ncid-*
        do
            name=`basename $script`
            pgrep -f $name > /dev/null 2>&1 && involk-rc.d $name restart
        done
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
