.\" %W% %G%
.TH NCID-TIVO 1
.SH NAME
.B ncid-tivo
- display Caller ID on TiVo using text2osd
.SH SYNOPSIS
ncid --no-gui --program
.B ncid-tivo
.SH DESCRIPTION
The
.B ncid-tivo
output module displays the Caller ID or message on a TiVo using text2osd.
.SH REQUIREMENTS
Hacked TiVo
.SH FILES
/etc/ncid/conf.d/ncid-tivo.conf
.br
/usr/share/ncid/ncid-tivo
.SH SEE ALSO
ncid.1,
ncidd.8
